---
'ALTERNATE_DRIVING_DIRECTION': 'False'
'AWS_REGION': 'cn-northwest-1'
'BEST_MODEL_METRIC': 'progress'
'BODY_SHELL_TYPE': 'deepracer'
'CAMERA_MAIN_ENABLE': 'True'
'CAMERA_SUB_ENABLE': 'False'
'CAR_COLOR': 'Red'
'CAR_NAME': 'FastCar'
'CHANGE_START_POSITION': 'True'
'DISPLAY_NAME': ''
'ENABLE_DOMAIN_RANDOMIZATION': 'False'
'ENABLE_EXTRA_KVS_OVERLAY': 'False'
'JOB_TYPE': 'TRAINING'
'KINESIS_VIDEO_STREAM_NAME': ''
'METRICS_S3_BUCKET': 'deepracerstandalone-models-v2-001698927672-cn-northwest-1'
'METRICS_S3_OBJECT_KEY': 'model-H9QWTZ6S1H/rl-deepracer-sagemaker/metrics/TrainingMetrics.json'
'MIN_EVAL_TRIALS': '5'
'MODEL_METADATA_FILE_S3_KEY': 'model-H9QWTZ6S1H/custom_files/model_metadata.json'
'NUM_WORKERS': '1'
'RACER_NAME': ''
'RACE_TYPE': 'TIME_TRIAL'
'REVERSE_DIR': 'False'
'REWARD_FILE_S3_KEY': 'model-H9QWTZ6S1H/custom_files/reward_function.py'
'ROBOMAKER_SIMULATION_JOB_ACCOUNT_ID': 'Dummy'
'ROUND_ROBIN_ADVANCE_DIST': '0.05'
'SAGEMAKER_SHARED_S3_BUCKET': 'deepracerstandalone-models-v2-001698927672-cn-northwest-1'
'SAGEMAKER_SHARED_S3_PREFIX': 'model-H9QWTZ6S1H/rl-deepracer-sagemaker'
'SIMTRACE_S3_BUCKET': 'deepracerstandalone-models-v2-001698927672-cn-northwest-1'
'SIMTRACE_S3_PREFIX': 'model-H9QWTZ6S1H/rl-deepracer-sagemaker'
'START_POSITION_OFFSET': '0.0'
'TRAINING_JOB_ARN': 'arn:Dummy'
'WORLD_NAME': 'reinvent_base'
